### ISSUE TITLE
Support normal class="..." syntax

### ISSUE THREAD

**Issue by jacob-8** [Simon-He95/tounocss#4]
Pretty cool stuff. I'd like to help get this linked on the UnoCSS docs but wanted to ask first if you could also support conversion to normal `class="bg-red"` syntax as not everybody uses attributify mode?

**Comment by Simon-He95** [comment]
Thank you very much for your suggestion, I agree with what you said, I have added the form used on the class in version v0.0.49

<img width="239" alt="image" src="https://github.com/Simon-He95/tounocss/assets/57086651/44816de5-cc93-4b35-acdd-69551662ca02">
