### ISSUE TITLE
支持自定义单位转换？

### ISSUE THREAD

**Issue by zouhangwithsweet** [Simon-He95/tounocss#6]
举个例子，现在的策略是，font-size: 32px 默认转换为 text-32px，能否通过配置使其转换为 text-8 ？

**Comment by Simon-He95** [comment]
<img width="85" alt="image" src="https://github.com/Simon-He95/tounocss/assets/57086651/ae7ebcc0-e611-4bd3-abda-db00473e1b75">
we will have the bottomBar to control isRem
